### PR TITLE
Updated deserializeBody middleware to also work on APIGatewayProxyEventV2 event types

### LINKED ISSUE #70: Allow deserializeBody to work with APIGatewayProxyEventV2
**Is your feature request related to a problem? Please describe.**
`deserializeBody()` currently assumes an event type `APIGatewayProxyEvent`. It would be helpful if it could also support APIGatewayProxyEventV2

** Would you be willing to help with a PR? **
- [x] Yes, absolutely
- [ ] Yes, with some guidance
- [ ] Unfortunately no time :'-(

## Describe the solution you'd like
Allow `deserializeBody()` to be used with handlers using events of type `APIGatewayProxyEventV2`

## Describe alternatives you've considered
I would be happy to extend this PR to include all APIGateway Proxy Event types (e.g., `APIGatewayProxyEventV2WithJWTAuthorizer`) as well (perhaps by creating a union type that's reused throughout the library), or to create a follow-on PR that accomplishes this

### PR DESCRIPTION
**Pull request by abmohan**
Closes #70 

## Checklist:
- [x] I have updated the documentation accordingly. 
(nothing to update here)
- [x] I have read the **CONTRIBUTING** document. 
(apologies if I missed something; please let me know if I did)

### CODE REVIEW

**Comment by abmohan** [comment]
@dbartholomae took a stab at this. It's my first time making a PR to the repo and using the tooling (e.g., `rush`). 

How does it look? Apologies if it's not the format and process you were looking for; I'm happy to revise as necessary. 

Also, do we have a discord server available?

**Comment by dbartholomae** [comment]
Thanks! I'll take a closer look on the weekend :)

**Comment by dbartholomae** [comment]
Thanks for taking a stab at this! Unfortunately, I don't think it's this simple:

To be able to use the middleware with an `APIGatewayProxyEventV2`, the `src/JsonDeserializer.ts` would need to accept events that extend `APIGatewayProxyEventV2`, not only `APIGatewayProxyEvent`. I don't think changing only the internal types would make a difference.

Unfortunately this would mean that also the handler return type and the handler event type would need to be adjusted.

This becomes a bit complicated, because both types need to exist next to each other: If the incoming event is an `APIGatewayProxyEvent`, then the handler needs to get `APIGatewayProxyObjectEvent<APIGatewayProxyEvent>`, but if the incoming event is an `APIGatewayProxyEventV2`, then the handler needs to get `APIGatewayProxyObjectEvent<APIGatewayProxyEventV2>`.

I'm not sure how to best solve this off the back of my head. Ideally, we could  reduce the required type to just the parts that are actually needed for the middleware, something like
```
{
    body?: string | null;
    headers?: Record<string, string>;
    isBase64Encoded: boolean;
  }
  ```
  
  I haven't checked yet whether this would work, though.

**Comment by abmohan** [comment]
Cool makes sense. I'll take a stab at this later this week!

**Pull request closed without merging**
